version: "3.1"
volumes:
    mysql-data:
services:
    php:
        build:
            context: .
            dockerfile: docker/Dockerfile
        container_name: test_php
        image: test_php
        hostname: test.loc
        tty: true
        volumes:
            - .:/home/test
            - ./docker/php.ini:/usr/local/etc/php/php.ini
            - ./var/composer:/root/.composer

    mysql:
        image: mysql:5.7
        container_name: test_mysql
        tty: true
        restart: always
        ports:
            - "3308:3306"
        environment:
            MYSQL_USER: anna
            MYSQL_PASSWORD: pass
            MYSQL_DATABASE: test_db
            MYSQL_RANDOM_ROOT_PASSWORD: 1
        volumes:
            - mysql-data:/var/lib/mysql

    web:
        image: nginx:latest
        container_name: test_web
        hostname: test.loc
        tty: true
        ports:
            - "8088:80"
        volumes:
            - .:/home/test:ro
            - ./docker/web.conf:/etc/nginx/conf.d/default.conf
